version: "3.7"

services:

  elasticsearch:
    image: elasticsearch:8.3.1
    container_name: elasticsearch
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: kibana:8.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: logstash:8.3.1 
    volumes:
      - ./configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/pipeline:/usr/share/logstash/pipeline
      - ./data/logstash:/var/lib/logstash
    ports:
      - "5044:5044/tcp"
      - "5044:5044/udp"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk: